"""
Generate documentation for a site based on the device settings that are part of that site.

Example:

Site Documentation – [Site Name]
1. Site Overview

    Location: [Address / Coordinates]
    Purpose: [Brief description of the site’s function]
    Site Manager / Contact: [Name and contact details]
    Date of Report: [YYYY-MM-DD]
    Summary:
    A brief narrative describing the site’s role in the network, key capabilities, and any special notes (e.g., planned upgrades or known issues).

2. Device Inventory

A comprehensive list of all devices present at the site.
Device Name	Device Type	Model	Serial Number	Status	IP Address	Rack/Position
Example-SW1	Switch	XYZ	ABC123	Active	192.168.1.2	Rack 1, U3-5
Example-RTR1	Router	ABC	DEF456	Active	192.168.1.1	Rack 2, U1-2
…	…	…	…	…	…	…

Additional sections or separate tables can be used to group devices by type (e.g., routers, switches, firewalls, servers, etc.).
3. Device Configurations

Overview of key configuration details for each device or groups of devices.

    Firmware/Software Versions:
    List or table showing each device’s current firmware or software release.

    Configuration Snapshots:
    Links or embedded snippets of critical configurations (e.g., routing protocols, VLAN setups, security settings).

    Custom Settings:
    Notes on any deviations from standard configurations or unique settings applied to devices.

4. Connectivity & Network Topology

Details on how devices interconnect and communicate.

    Physical Connectivity:
        Cabling: Types (fiber, copper), port details, and connection diagrams.
        Link Speeds: Where applicable, include speed and duplex details.
    Logical Connectivity:
        VLANs/Subnets: Overview of the VLAN assignments and IP addressing schemes.
        Routing Protocols: Brief summary of routing or redundancy protocols (HSRP/VRRP, OSPF, BGP, etc.).
    Diagrams:
    An embedded network topology diagram (or reference to a generated image file) showing inter-device links.

5. Power & Environmental

Information on the power infrastructure and environmental conditions at the site.

    Power Distribution:
        UPS/PDUs: Models, capacities, and current status.
        Power Circuits: Which devices are on which circuits, including any redundancy details.
    Environmental Monitoring:
        Temperature & Humidity: Current readings and thresholds.
        Cooling Systems: Overview of CRAC units or other cooling solutions.

6. Rack Layouts

Detailed view of the physical placement of devices in racks.

    Rack Inventory:
    For each rack:
        Rack ID: Identifier or location.
        U Positions: A table or diagram showing which devices are mounted in which U positions.

    Diagrams:
    Front and back views of rack layouts (images or schematics).

    Cable Management:
    Summary of patch panels, cable routes, and any labeling standards applied.

7. Additional Information & Alerts

Any other details that might be useful for operational teams.

    Maintenance & Monitoring:
        Scheduled maintenance dates, recent activity logs.
        Known issues or alerts generated by monitoring systems.

    Change Log:
    Summary of recent configuration or hardware changes.

    Contact Details:
    Quick reference for key NOC and engineering personnel.
"""
