apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 3.0.0

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: Prometheus
          matcherRegex: "device=([^ ]+)"
          name: Device
          url: ""

  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    editable: false
    jsonData:
      implementation: prometheus

  - name: Nautobot-Infinity
    type: yesoreyeram-infinity-datasource
    uid: nautobot-infinity
    access: proxy
    editable: false
    jsonData:
      auth_method: "apiKey"
      apiKeyType: "header"
      apiKeyKey: "Authorization"
      allowedHosts:
        - "nautobot:8080"
    secureJsonData:
      apiKeyValue: "Token ${NAUTOBOT_SUPERUSER_API_TOKEN}"

  - name: Topology-Infinity
    type: yesoreyeram-infinity-datasource
    uid: topology-infinity
    access: proxy
    editable: false
    jsonData:
      auth_method: "none"
      allowedHosts: []
