"""Purpose: Generate codified monitoring targets, rules, and dashboards."""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import requests
import yaml
from nautobot.apps.jobs import BooleanVar, Job, StringVar, register_jobs
from nautobot.dcim.models import Device
from .topology_dashboard_sync import generate_topology_artifacts, DEFAULT_TOPOLOGY_OUTPUT_DIR


name = "Monitoring"

DEFAULT_TARGETS_PATH = "/opt/nautobot/prometheus_file_sd/nautobot_targets.yml"
DEFAULT_TELEGRAF_TARGETS_PATH = "/tmp/nautobot_telegraf_targets.conf"
DEFAULT_CONTRACT_PATH = "/opt/nautobot/scripts/visualization/monitoring_contract.yaml"
DEFAULT_GENERATOR_PATH = "/opt/nautobot/scripts/visualization/generate_visualizations.py"
DEFAULT_ALERTS_PATH = "/opt/nautobot/monitoring/alerts/generated_visualization.yml"
DEFAULT_RECORDING_PATH = "/opt/nautobot/monitoring/recording_rules/generated_visualization.yml"
DEFAULT_DASHBOARDS_DIR = "/opt/nautobot/monitoring/grafana_dashboards"


class MonitoringVisualizationSync(Job):
    """Run end-to-end monitoring visualization generation from Nautobot inventory."""

    targets_output_path = StringVar(
        description="Path for Prometheus file_sd targets generated from Nautobot inventory",
        default=DEFAULT_TARGETS_PATH,
    )
    contract_path = StringVar(
        description="Monitoring contract YAML path",
        default=DEFAULT_CONTRACT_PATH,
    )
    alerts_output_path = StringVar(
        description="Generated Prometheus alerts YAML path",
        default=DEFAULT_ALERTS_PATH,
    )
    recording_rules_output_path = StringVar(
        description="Generated Prometheus recording rules YAML path",
        default=DEFAULT_RECORDING_PATH,
    )
    dashboards_output_dir = StringVar(
        description="Grafana dashboards output directory",
        default=DEFAULT_DASHBOARDS_DIR,
    )
    telegraf_targets_output_path = StringVar(
        description="Path for generated Telegraf dynamic input config",
        default=DEFAULT_TELEGRAF_TARGETS_PATH,
    )
    topology_output_dir = StringVar(
        description="Directory for generated topology dashboard artifacts",
        default=DEFAULT_TOPOLOGY_OUTPUT_DIR,
    )
    sync_topology = BooleanVar(
        description="Generate topology dashboard artifacts from Nautobot inventory/cabling",
        default=True,
    )
    write_targets = BooleanVar(
        description="Generate and write Prometheus file_sd targets from Nautobot inventory",
        default=True,
    )
    reload_prometheus = BooleanVar(
        description="Trigger Prometheus config reload endpoint after generation",
        default=False,
    )
    dry_run = BooleanVar(
        description="Preview generation without writing files",
        default=True,
    )

    class Meta:
        name = "Monitoring Visualization Sync"
        description = (
            "Generate codified Prometheus target discovery, alert rules, recording rules, "
            "and Grafana dashboards from Nautobot inventory and monitoring contract."
        )
        has_sensitive_variables = False
        soft_time_limit = 600
        time_limit = 900
        task_queues = ["default", "priority"]

    def _build_targets(self, output_path: str, dry_run: bool = True) -> str:
        devices = Device.objects.filter(primary_ip4__isnull=False).select_related("role", "platform", "location")
        config = []
        for dev in devices:
            labels = {
                "device": dev.name,
                "role": dev.role.name.lower().replace(" ", "-") if dev.role else "unknown",
                "platform": dev.platform.network_driver if dev.platform else "unknown",
                "location": dev.location.name if dev.location else "unknown",
            }
            # For blackbox probing, target should be raw device IP.
            config.append({"targets": [str(dev.primary_ip4.host)], "labels": labels})

        rendered = yaml.safe_dump(config, sort_keys=True)
        self.logger.info(f"Built {len(config)} targets from Nautobot inventory.")
        if dry_run:
            self._write_preview("prometheus_targets_preview.yml", rendered)
            return rendered

        p = Path(output_path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(rendered, encoding="utf-8")
        self.logger.info(f"Wrote Prometheus targets to {output_path}")
        return rendered

    def _build_telegraf_targets(self, output_path: str, dry_run: bool = True) -> str:
        devices = Device.objects.filter(primary_ip4__isnull=False).select_related("role", "platform", "location")
        lines = [
            "# Generated by MonitoringVisualizationSync job.",
            "# Do not edit manually.",
            "",
        ]
        for dev in devices:
            platform = dev.platform.network_driver if dev.platform else "unknown"
            role = dev.role.name.lower().replace(" ", "-") if dev.role else "unknown"
            location = dev.location.name if dev.location else "unknown"
            ip = dev.primary_ip4.host
            name = dev.name.replace('"', '\\"')
            platform = platform.replace('"', '\\"')
            role = role.replace('"', '\\"')
            location = location.replace('"', '\\"')
            lines.extend(
                [
                    "[[inputs.ping]]",
                    f'  urls = ["{ip}"]',
                    '  method = "exec"',
                    "  count = 3",
                    '  interval = "30s"',
                    "  timeout = 5.0",
                    "  [inputs.ping.tags]",
                    '    job = "icmp-probes"',
                    f'    device = "{name}"',
                    f'    location = "{location}"',
                    f'    platform = "{platform}"',
                    f'    role = "{role}"',
                    "",
                    "[[inputs.snmp]]",
                    f'  agents = ["udp://{ip}:161"]',
                    "  version = 2",
                    '  community = "${SNMP_COMMUNITY}"',
                    '  interval = "60s"',
                    '  timeout = "5s"',
                    "  retries = 1",
                    '  name = "interface"',
                    "  [inputs.snmp.tags]",
                    '    job = "snmp-devices"',
                    f'    device = "{name}"',
                    f'    location = "{location}"',
                    f'    platform = "{platform}"',
                    f'    role = "{role}"',
                    "  [[inputs.snmp.field]]",
                    '    name = "sysName"',
                    '    oid = "RFC1213-MIB::sysName.0"',
                    "    is_tag = true",
                    "  [[inputs.snmp.field]]",
                    '    name = "sysUpTime"',
                    '    oid = "RFC1213-MIB::sysUpTime.0"',
                    "  [[inputs.snmp.table]]",
                    '    name = "interface"',
                    '    inherit_tags = ["sysName"]',
                    "    [[inputs.snmp.table.field]]",
                    '      name = "ifIndex"',
                    '      oid = "IF-MIB::ifIndex"',
                    "      is_tag = true",
                    "    [[inputs.snmp.table.field]]",
                    '      name = "ifDescr"',
                    '      oid = "IF-MIB::ifDescr"',
                    "      is_tag = true",
                    "    [[inputs.snmp.table.field]]",
                    '      name = "ifAlias"',
                    '      oid = "IF-MIB::ifAlias"',
                    "      is_tag = true",
                    "    [[inputs.snmp.table.field]]",
                    '      name = "ifType"',
                    '      oid = "IF-MIB::ifType"',
                    "    [[inputs.snmp.table.field]]",
                    '      name = "ifAdminStatus"',
                    '      oid = "IF-MIB::ifAdminStatus"',
                    "    [[inputs.snmp.table.field]]",
                    '      name = "ifOperStatus"',
                    '      oid = "IF-MIB::ifOperStatus"',
                    "    [[inputs.snmp.table.field]]",
                    '      name = "ifLastChange"',
                    '      oid = "IF-MIB::ifLastChange"',
                    "    [[inputs.snmp.table.field]]",
                    '      name = "ifMtu"',
                    '      oid = "IF-MIB::ifMtu"',
                    "    [[inputs.snmp.table.field]]",
                    '      name = "ifSpeed"',
                    '      oid = "IF-MIB::ifSpeed"',
                    "    [[inputs.snmp.table.field]]",
                    '      name = "ifHighSpeed"',
                    '      oid = "IF-MIB::ifHighSpeed"',
                    "    [[inputs.snmp.table.field]]",
                    '      name = "ifHCInOctets"',
                    '      oid = "IF-MIB::ifHCInOctets"',
                    "    [[inputs.snmp.table.field]]",
                    '      name = "ifHCOutOctets"',
                    '      oid = "IF-MIB::ifHCOutOctets"',
                    "    [[inputs.snmp.table.field]]",
                    '      name = "ifHCInUcastPkts"',
                    '      oid = "IF-MIB::ifHCInUcastPkts"',
                    "    [[inputs.snmp.table.field]]",
                    '      name = "ifHCOutUcastPkts"',
                    '      oid = "IF-MIB::ifHCOutUcastPkts"',
                    "    [[inputs.snmp.table.field]]",
                    '      name = "ifHCInMulticastPkts"',
                    '      oid = "IF-MIB::ifHCInMulticastPkts"',
                    "    [[inputs.snmp.table.field]]",
                    '      name = "ifHCOutMulticastPkts"',
                    '      oid = "IF-MIB::ifHCOutMulticastPkts"',
                    "    [[inputs.snmp.table.field]]",
                    '      name = "ifHCInBroadcastPkts"',
                    '      oid = "IF-MIB::ifHCInBroadcastPkts"',
                    "    [[inputs.snmp.table.field]]",
                    '      name = "ifHCOutBroadcastPkts"',
                    '      oid = "IF-MIB::ifHCOutBroadcastPkts"',
                    "    [[inputs.snmp.table.field]]",
                    '      name = "ifInDiscards"',
                    '      oid = "IF-MIB::ifInDiscards"',
                    "    [[inputs.snmp.table.field]]",
                    '      name = "ifOutDiscards"',
                    '      oid = "IF-MIB::ifOutDiscards"',
                    "    [[inputs.snmp.table.field]]",
                    '      name = "ifInErrors"',
                    '      oid = "IF-MIB::ifInErrors"',
                    "    [[inputs.snmp.table.field]]",
                    '      name = "ifOutErrors"',
                    '      oid = "IF-MIB::ifOutErrors"',
                    "",
                ]
            )

        rendered = "\n".join(lines)
        if dry_run:
            self._write_preview("telegraf_targets_preview.conf", rendered)
            return rendered
        p = Path(output_path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(rendered, encoding="utf-8")
        self.logger.info(f"Wrote Telegraf dynamic config to {output_path}")
        return rendered

    def _run_generator(
        self,
        contract_path: str,
        targets_path: str,
        alerts_path: str,
        recording_path: str,
        dashboards_dir: str,
        dry_run: bool,
    ) -> str:
        cmd = [
            "python3",
            DEFAULT_GENERATOR_PATH,
            "--contract",
            contract_path,
            "--targets-file",
            targets_path,
            "--alerts-out",
            alerts_path,
            "--recording-rules-out",
            recording_path,
            "--dashboards-out-dir",
            dashboards_dir,
        ]
        if dry_run:
            cmd.append("--dry-run")

        generator_path = Path(DEFAULT_GENERATOR_PATH)
        if dry_run and not generator_path.exists():
            output = f"Generator skipped: {generator_path} is not available in this environment."
            self.logger.warning(output)
            return output

        proc = subprocess.run(cmd, capture_output=True, text=True, check=False)
        output = (proc.stdout or "") + (proc.stderr or "")
        if proc.returncode != 0:
            raise RuntimeError(f"Generator failed ({proc.returncode}): {output}")
        return output

    def _write_preview(self, filename: str, content: str) -> None:
        try:
            self.create_file(filename, content)
        except Exception:
            self.logger.info(f"Preview artifact generated but not attached: {filename}")

    def run(
        self,
        targets_output_path=DEFAULT_TARGETS_PATH,
        contract_path=DEFAULT_CONTRACT_PATH,
        alerts_output_path=DEFAULT_ALERTS_PATH,
        recording_rules_output_path=DEFAULT_RECORDING_PATH,
        dashboards_output_dir=DEFAULT_DASHBOARDS_DIR,
        telegraf_targets_output_path=DEFAULT_TELEGRAF_TARGETS_PATH,
        topology_output_dir=DEFAULT_TOPOLOGY_OUTPUT_DIR,
        sync_topology=True,
        write_targets=True,
        reload_prometheus=False,
        dry_run=True,
    ):
        if write_targets:
            self._build_targets(targets_output_path, dry_run=dry_run)
            self._build_telegraf_targets(telegraf_targets_output_path, dry_run=dry_run)
        if sync_topology:
            payload, files = generate_topology_artifacts(Path(topology_output_dir), dry_run=dry_run)
            self.logger.info(
                f"Topology payload built: nodes={len(payload['all']['nodes'])} "
                f"edges={len(payload['all']['edges'])} locations={len(payload['all']['locations'])}"
            )
            self._write_preview("topology_all_preview.json", yaml.safe_dump(payload["all"], sort_keys=False))
            if not dry_run:
                self.logger.info(f"Topology artifacts written: {files}")

        generator_output = self._run_generator(
            contract_path=contract_path,
            targets_path=targets_output_path,
            alerts_path=alerts_output_path,
            recording_path=recording_rules_output_path,
            dashboards_dir=dashboards_output_dir,
            dry_run=dry_run,
        )
        self.logger.info(generator_output.strip())
        self._write_preview("visualization_sync_output.txt", generator_output)

        if reload_prometheus and not dry_run:
            prometheus_url = os.getenv("PROMETHEUS_INTERNAL_URL", "http://prometheus:9090")
            resp = requests.post(f"{prometheus_url}/-/reload", timeout=10)
            if resp.status_code >= 300:
                raise RuntimeError(f"Prometheus reload failed with status {resp.status_code}")
            self.logger.info("Prometheus reload triggered successfully.")


register_jobs(MonitoringVisualizationSync)
